export const formSchema = [
  {
    id: "requestorInfo",
    type: "section",
    label: "Requestor Info (You)",
    fields: [
      {
        id: "name",
        type: "text",
        label: "First & Last Name",
        required: true,
      },
      {
        id: "phone",
        type: "tel",
        label: "Phone Number",
        required: true,
      },
      {
        id: "email",
        type: "email",
        label: "E-mail Address",
        required: true,
      },
    ],
  },
  {
    id: "serviceTypes",
    type: "section",
    label: "Select Service Types",
    fields: [
      {
        id: "medicalSupport",
        type: "checkbox",
        label: "Medical Support",
        fields: [
          {
            id: "medicalStaffCount",
            type: "number",
            label: "Number of Staff Requested",
            required: true,
            condition: { field: "medicalSupport", value: true },
          },
          {
            id: "medicalServiceOptions",
            type: "multiselect",
            label: "Medical Service Options",
            options: [
              { value: "EMT", label: "EMT" },
              { value: "PARAMEDIC", label: "PARAMEDIC" },
              { value: "NURSE", label: "NURSE" },
              { value: "PHYSICIAN", label: "PHYSICIAN" },
              { value: "BLS_AMBULANCE", label: "BLS AMBULANCE" },
              { value: "ALS_AMBULANCE", label: "ALS AMBULANCE" },
              { value: "SET_MEDIC", label: "SET MEDIC" },
              { value: "LIFEGUARD", label: "LIFEGUARD" },
              { value: "CONSTRUCTION_MEDIC", label: "CONSTRUCTION MEDIC" },
            ],
            required: true,
            condition: { field: "medicalSupport", value: true },
          },
        ],
      },
      {
        id: "emergencyManagement",
        type: "checkbox",
        label: "Emergency Management",
        fields: [
          {
            id: "emergencyManagementOptions",
            type: "select",
            label: "Emergency Management Options",
            options: [
              { value: "option1", label: "Option 1" },
              { value: "option2", label: "Option 2" },
              { value: "option3", label: "Option 3" },
            ],
            required: true,
            condition: { field: "emergencyManagement", value: true },
          },
        ],
      },
      {
        id: "covidCompliance",
        type: "checkbox",
        label: "COVID Compliance",
        fields: [
          {
            id: "covidStaffCount",
            type: "number",
            label: "Number of Staff Requested",
            required: true,
            condition: { field: "covidCompliance", value: true },
          },
          {
            id: "covidComplianceOptions",
            type: "multiselect",
            label: "Covid Compliance Options",
            options: [
              { value: "CCO", label: "Covid Compliance Officer (CCO)" },
              { value: "VACCINATION_VERIFIER", label: "Vaccination Verifier" },
            ],
            required: true,
            condition: { field: "covidCompliance", value: true },
          },
        ],
      },
      {
        id: "covidTesting",
        type: "checkbox",
        label: "Covid Testing",
        fields: [
          {
            id: "estimatedTestCount",
            type: "number",
            label: "Estimated Number of Tests",
            required: true,
            condition: { field: "covidTesting", value: true },
          },
        ],
      },
    ],
  },
  {
    id: "projectDetails",
    type: "section",
    label: "Project Details",
    fields: [
      {
        id: "state",
        type: "text",
        label: "What state are these services being requested in?",
        required: true,
      },
      {
        id: "projectName",
        type: "text",
        label: "Project/Event Name",
        required: true,
      },
      {
        id: "projectType",
        type: "select",
        label: "Project Type",
        options: [
          { value: "INDOOR_CONCERT", label: "Indoor Concert Performance" },
          { value: "OUTDOOR_CONCERT", label: "Outdoor Concert / Performance" },
          { value: "MARATHON", label: "Marathon / Run / Race" },
          { value: "MUSIC_FESTIVAL", label: "Music Festival" },
          { value: "SPORTING_EVENT", label: "Sporting Event" },
          { value: "NIGHTLIFE_EVENT", label: "Nightlife Event" },
          { value: "CONSTRUCTION", label: "Construction-Related" },
          { value: "GALA", label: "Gala Awards Ceremony" },
          { value: "MARKETING", label: "Marketing Activation" },
          { value: "PHOTO_FILM", label: "Photo / Film Shoot" },
          { value: "WEDDING", label: "Wedding" },
          { value: "PROTEST", label: "Protest / Demonstration" },
          { value: "RECREATIONAL", label: "Recreational Event" },
        ],
        required: true,
      },
      {
        id: "locationAddress",
        type: "textarea",
        label: "Location Address",
        required: true,
      },
      {
        id: "eventDate",
        type: "date",
        label: "Event Date",
        required: true,
      },
      {
        id: "multiDayEvent",
        type: "checkbox",
        label: "Multi-Day Event",
        fields: [
          {
            id: "endDate",
            type: "date",
            label: "End Date",
            required: true,
            condition: { field: "multiDayEvent", value: true },
          },
        ],
      },
      {
        id: "estimatedAttendees",
        type: "number",
        label: "Estimated Number of Attendees",
        required: true,
      },
      {
        id: "onSiteContactName",
        type: "text",
        label: "On-Site Contact Name",
        required: true,
      },
      {
        id: "onSiteContactPhone",
        type: "tel",
        label: "On-Site Contact Phone",
        required: true,
      },
      {
        id: "additionalNotes",
        type: "textarea",
        label: "Additional Notes & Info",
        required: false,
      },
    ],
  },
  {
    id: "billingInfo",
    type: "section",
    label: "Billing Information",
    fields: [
      {
        id: "companyName",
        type: "text",
        label: "Company Name",
        required: true,
      },
      {
        id: "billingContactName",
        type: "text",
        label: "Billing Contact Name",
        required: true,
      },
      {
        id: "billingPhone",
        type: "tel",
        label: "Phone Number",
        required: true,
      },
      {
        id: "billingEmail",
        type: "email",
        label: "E-mail Address",
        required: true,
      },
    ],
  },
];
